#!/usr/bin/env python3
"""
Query sample manifest generated by workbook_sample.py.

Usage:
    python skills/xlsx/scripts/workbook_manifest_query.py output/samples/sample_manifest.json --list
    python skills/xlsx/scripts/workbook_manifest_query.py output/samples/sample_manifest.json --sheet "Inputs & Assumptions"
    python skills/xlsx/scripts/workbook_manifest_query.py output/samples/sample_manifest.json --contains assumptions
"""

import argparse
import json
import re
import sys
from pathlib import Path


def normalize(text):
    return re.sub(r"[^a-z0-9]+", "", text.lower())


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("manifest")
    parser.add_argument("--list", action="store_true", help="List all sheets and sample files")
    parser.add_argument("--sheet", help="Exact or normalized sheet name match")
    parser.add_argument("--contains", help="Substring search on sheet name")
    args = parser.parse_args()

    manifest_path = Path(args.manifest).expanduser()
    if not manifest_path.exists():
        print(json.dumps({"status": "error", "error": f"Manifest not found: {manifest_path}"}))
        sys.exit(1)

    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    samples = data.get("samples", [])
    if not isinstance(samples, list):
        print(json.dumps({"status": "error", "error": "Invalid manifest: samples must be an array"}))
        sys.exit(1)

    rows = []
    for s in samples:
        sheet_name = s.get("sheet_name")
        rows.append({
            "sheet_name": sheet_name,
            "sheet_name_normalized": normalize(str(sheet_name)),
            "sheet_index": s.get("sheet_index"),
            "sample_files": s.get("sample_files"),
            "rows_written": s.get("rows_written"),
            "strategy": s.get("strategy"),
            "source_max_row": s.get("source_max_row"),
            "source_max_col": s.get("source_max_col"),
        })

    if args.list:
        print(json.dumps({"status": "success", "count": len(rows), "rows": rows}, indent=2))
        return

    if args.sheet:
        target_norm = normalize(args.sheet)
        exact = [r for r in rows if r["sheet_name"] == args.sheet]
        norm = [r for r in rows if r["sheet_name_normalized"] == target_norm]
        matches = exact if exact else norm
        print(json.dumps({"status": "success", "query": args.sheet, "matches": matches}, indent=2))
        return

    if args.contains:
        q = args.contains.lower()
        matches = [r for r in rows if q in str(r["sheet_name"]).lower()]
        print(json.dumps({"status": "success", "query": args.contains, "matches": matches}, indent=2))
        return

    print(json.dumps({
        "status": "error",
        "error": "Provide one of: --list, --sheet, --contains",
    }))
    sys.exit(1)


if __name__ == "__main__":
    main()
